Add scripts to upload and download files to pvcs

diff --git a/src/scripts/krsync b/src/scripts/krsync
--- a/src/scripts/krsync
+++ b/src/scripts/krsync
@@ -2,7 +2,17 @@
 
 if [ -z "$KRSYNC_STARTED" ]; then
     export KRSYNC_STARTED=true
-    exec rsync --blocking-io --rsh "$0" $@
+    while [ 1 ]
+    do
+        exec rsync --blocking-io --rsh "$0" $@
+        if [ "$?" = "0" ] ; then
+        echo "rsync completed normally"
+        exit
+        else
+        echo "Rsync failure. Backing off and retrying..."
+        sleep 180
+        fi
+    done
 fi
 
 # Running as --rsh
@@ -17,5 +27,4 @@ if [ "X$pod" = "X-l" ]; then
     namespace="-n $1"
     shift
 fi
-
 exec kubectl $namespace exec -i $pod -- "$@"
